#Assumes Node.js React Frontend, Express.js API server, & PostgreSQL Database

volumes:
  postgres_volume:
  node_modules:

services:
  frontend:
  # GUI
    build: frontend/
    container_name: 'frontend'
    depends_on:
      - backend
      - database
    env_file:
      - .env
    environment:
      - VITE_PORT=${VITE_PORT}
    ports:
      - ${VITE_PORT}:5173
      # 5173 is the default Node.js server, change if ports have been changed to something like 8080
    volumes:
      - type: bind
        source: ./frontend/src
        target: /frontend/src
      - node_modules:/frontend/node_modules
    networks:
      - appnetwork
  backend:
    # Backend Express Server
    build: backend/
    container_name: 'backend'
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - EXPRESS_PORT=${EXPRESS_PORT}
    ports:
      - ${EXPRESS_PORT}:3000
      # 3000 is default Express.js port, again - change if application has something different
    volumes:
      - type: bind
        source: ./backend
        target: /backend
    networks:
      - appnetwork
  database:
    image: postgres
    container_name: database
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      #- PGUSER=postgres #For Health Check
      # Any environment variables from within the .env file (this file is in the .gitignore, must be made locally with variables matching)
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USERNAME} -d ${POSTGRES_DB_NAME}'" ]
      interval: 1s
      timeout: 3s
      retries: 3
    networks:
      - appnetwork
networks:
  appnetwork:
    driver: bridge